export const SEARCH_GAME = 'SEARCH_GAME';
export const SEARCH_CHANNEL = 'SEARCH_CHANNEL';
export const RECEIVE_GAMES = 'RECEIVE_GAMES';
export const RECEIVE_CHANNELS = 'RECEIVE_CHANNELS';
export const RESET_LIST_OF_GAMES = 'RESET_LIST_OF_GAMES';
